on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: '25'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.12.4.1607'
      - uses: actions/cache@v5.0.3
        with:
          path: '~/.m2'
          key: "${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}"
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: yarn install
      - run: clojure -M:cljfmt check
      - run: clojure -M:clj-kondo
      - run: yarn test
  deploy:
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: '25'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.12.4.1607'
      - uses: actions/cache@v5.0.3
        with:
          path: '~/.m2'
          key: "${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}"
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: sudo apt install --no-install-recommends inkscape
      - name: Build artifacts
        run: |
          clojure -Stree
          yarn install
          yarn release
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          branch: gh-pages
          folder: resources/public
