on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-java@v3.5.0
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.11.1.1155'
      - uses: actions/cache@v3.0.8
        with:
          path: '~/.m2'
          key: "${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}"
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: clojure -M:cljfmt check
      - run: clojure -M:clj-kondo
  deploy:
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-java@v3.5.0
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.11.1.1155'
      - uses: actions/cache@v3.0.8
        with:
          path: '~/.m2'
          key: "${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}"
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build artifacts
        run: |
          clojure -Stree
          make
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: resources/public
